# Generated by Django 5.1 on 2024-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savecontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=32)),
                ('subject', models.CharField(max_length=40)),
                ('message', models.TextField(max_length=50)),
            ],
        ),
    ]
