# Generated by Django 5.1 on 2024-09-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=30)),
                ('year', models.IntegerField(max_length=20)),
                ('review', models.TextField(max_length=5)),
            ],
        ),
    ]
